//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_UX.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DE() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projet_UX.Resources.DE", typeof(DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hinzufügen.
        /// </summary>
        internal static string btnAddTickets {
            get {
                return ResourceManager.GetString("btnAddTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fahrkarte zum Flughafen
        ///                   Roissy-Charles De Gaulle, Orly.
        /// </summary>
        internal static string btnAeroport {
            get {
                return ResourceManager.GetString("btnAeroport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weiter.
        /// </summary>
        internal static string btnContinue {
            get {
                return ResourceManager.GetString("btnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fahrkarte für Disneyland Paris
        ///                    Gültig ab dieser Station.
        /// </summary>
        internal static string btnDisneyland {
            get {
                return ResourceManager.GetString("btnDisneyland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        internal static string btnFrench {
            get {
                return ResourceManager.GetString("btnFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deustch.
        /// </summary>
        internal static string btnGerman {
            get {
                return ResourceManager.GetString("btnGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Italiano.
        /// </summary>
        internal static string btnItalian {
            get {
                return ResourceManager.GetString("btnItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paris Besuch
        ///                   1 bis 5 Tage.
        /// </summary>
        internal static string btnParisVisite {
            get {
                return ResourceManager.GetString("btnParisVisite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bezahlen.
        /// </summary>
        internal static string btnPay {
            get {
                return ResourceManager.GetString("btnPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ermäßigtes Ticket.
        /// </summary>
        internal static string btnReduced {
            get {
                return ResourceManager.GetString("btnReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Español.
        /// </summary>
        internal static string btnSpanish {
            get {
                return ResourceManager.GetString("btnSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Standard-Ticket.
        /// </summary>
        internal static string btnStandard {
            get {
                return ResourceManager.GetString("btnStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fahrkarte t+
        ///                   Métro, Tram, Bus, RER in Paris.
        /// </summary>
        internal static string btnTplus {
            get {
                return ResourceManager.GetString("btnTplus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string btnUk {
            get {
                return ResourceManager.GetString("btnUk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hier sind die von Ihnen ausgewählten Scheine.
        /// </summary>
        internal static string lblBasket {
            get {
                return ResourceManager.GetString("lblBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Beschreibung.
        /// </summary>
        internal static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bis.
        /// </summary>
        internal static string lblFinish {
            get {
                return ResourceManager.GetString("lblFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wählen Sie die gewünschte Sprache aus.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ticketpreise.
        /// </summary>
        internal static string lblPriceNbTickets {
            get {
                return ResourceManager.GetString("lblPriceNbTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zusammenfassung.
        /// </summary>
        internal static string lblRecapitulatif {
            get {
                return ResourceManager.GetString("lblRecapitulatif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduzierter Preis.
        /// </summary>
        internal static string lblReduced {
            get {
                return ResourceManager.GetString("lblReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Standartpreis.
        /// </summary>
        internal static string lblStandard {
            get {
                return ResourceManager.GetString("lblStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wählen Sie das gewünschte Ticket aus.
        /// </summary>
        internal static string lblTicket {
            get {
                return ResourceManager.GetString("lblTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Anzahl der Tickets.
        /// </summary>
        internal static string lblTicketsNumbers {
            get {
                return ResourceManager.GetString("lblTicketsNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gesamtpreis.
        /// </summary>
        internal static string lblTotalPrice {
            get {
                return ResourceManager.GetString("lblTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validieren Sie es.
        /// </summary>
        internal static string lblValidDate {
            get {
                return ResourceManager.GetString("lblValidDate", resourceCulture);
            }
        }
    }
}
